common/models/Service.php
<?php

namespace common\models;

use Yii;
use \common\models\base\Service as BaseService;
use yii\behaviors\SluggableBehavior;
use yii\helpers\ArrayHelper;

/**
 * This is the model class for table "service".
 */
class Service extends BaseService
{
    public $image_file;

    public function behaviors()
    {
        return ArrayHelper::merge(
            parent::behaviors(),
            [
                [
                    'class' => SluggableBehavior::className(),
                    'attribute' => 'name',
                    'slugAttribute' => 'alias',
                    'immutable' => true
                ],
            ]
        );
    }

    public function rules()
    {
        return ArrayHelper::merge(
             parent::rules(),
             [
                 ['image_file', 'image', 'extensions' => 'jpg, gif, png, jpeg']
             ]
        );
    }

    public function getPersonal() {
        return $this->hasMany(Personal::className(), ['id' => 'personal_id'])
            ->viaTable('personal_has_service', ['service_id' => 'id']);
    }
}

common/models/Textpage.php
<?php

namespace common\models;

use Yii;
use \common\models\base\Textpage as BaseTextpage;
use yii\behaviors\SluggableBehavior;
use yii\helpers\ArrayHelper;
use yii\helpers\Url;

/**
 * This is the model class for table "textpage".
 */
class Textpage extends BaseTextpage
{

public function behaviors()
    {
        return ArrayHelper::merge(
            parent::behaviors(),
            [
                [
                    'class' => SluggableBehavior::className(),
                    'attribute' => 'name',
                    'slugAttribute' => 'alias',
                    'immutable' => true
                ],
            ]
        );
    }

    public function rules()
    {
        return ArrayHelper::merge(
             parent::rules(),
             [
                  # custom validation rules
             ]
        );
    }

    public static function liLink($id, $class) {
        $model = Textpage::findOne($id);

        if ($_SERVER['REQUEST_URI'] == '/'.$model->alias.Yii::$app->get('urlManager')->suffix) {
            $active = ' class="active"';
        } else {
            $active = '';
        }

        return '<li'.$active.'><a href="'.Url::to(['textpage/index', 'alias' => $model->alias]).'" class="'.$class.'"><span>'.$model->name.'</span></a></li>';
    }
}

backend/controllers/TextpageController.php
<?php

namespace backend\controllers;

use yii\filters\AccessControl;

/**
* This is the class for controller "TextpageController".
*/
class TextpageController extends \backend\controllers\base\TextpageController
{

    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }

}

frontend/controllers/TextpageController.php
<?php
namespace frontend\controllers;

use common\models\Service;
use common\models\Serviceitem;
use common\models\Textpage;
use HttpException;
use Yii;
use yii\web\Controller;
use yii\web\NotFoundHttpException;

/**
 * Site controller
 */
class TextpageController extends Controller
{
    public function actionIndex($alias)
    {
        if ($model = Textpage::find()->where(['alias' => $alias])->one()) {
            $view = '';

            if ($model->id == 1) {
                $view = 'about';
            } else if ($model->id == 2) {
                $view = 'contacts';
            }

            return $this->render($view, [
                'model' => $model,
            ]);
        }

        if ($model = Service::find()->where(['alias' => $alias])->one()) {
            $serviceItems = Serviceitem::find()->where(['service_id' => $model->id])->all();

            return $this->render('service', [
                'model' => $model,
                'serviceItems' => $serviceItems,
            ]);
        }

        throw new NotFoundHttpException();
    }
}

frontend/views/textpage/about.php
<?php

$this->params['seo_title'] = $model->seo_title;
$this->params['seo_description'] = $model->seo_description;
$this->params['seo_keywords'] = $model->seo_keywords;
$this->params['name'] = $model->name;

?>
<div class="header2">О студии</div>

<div class="advantages">
    <div class="advantages__inner">
        <div class="advantages__item">
            <div class="advantages__itemImage" style="background-image: url(/img/a1.png);"></div>
            <div class="advantages__itemInfo">
                <div class="advantages__itemHeader">Квалифицированные
                    специалисты</div>
                <div class="advantages__itemText">Приходите и убедитесь в профессионализме наших мастеров и доступности наших услуг!</div>
            </div>
        </div>
        <div class="advantages__item">
            <div class="advantages__itemImage" style="background-image: url(/img/a2.png);"></div>
            <div class="advantages__itemInfo">
                <div class="advantages__itemHeader">Лучшие материалы</div>
                <div class="advantages__itemText">Работаем только с лучшими материалами и напрямую с представителями марок,  что гарантирует качество материал.</div>
            </div>
        </div>
        <div class="advantages__item">
            <div class="advantages__itemImage" style="background-image: url(/img/a3.png);"></div>
            <div class="advantages__itemInfo">
                <div class="advantages__itemHeader">Безопасность</div>
                <div class="advantages__itemText">Все инструменты проходят обязательную стерилизацию, что гарантирует безопасность всех процедур.</div>
            </div>
        </div>
        <div class="advantages__item">
            <div class="advantages__itemImage" style="background-image: url(/img/a4.png);"></div>
            <div class="advantages__itemInfo">
                <div class="advantages__itemHeader">Онлайн-запись</div>
                <div class="advantages__itemText">В любое время Вы можете записаться на любую услугу нашей студии и моментально получить подтверждение с помощью «Онлайн-записи»</div>
            </div>
        </div>
    </div>
</div>

<?=$this->render('@frontend/views/blocks/gallery')?>

<?=$this->render('@frontend/views/blocks/masters')?>

frontend/views/textpage/contacts.php
<?php

use frontend\models\CallbackForm;
use yii\widgets\ActiveForm;

$this->params['seo_title'] = $model->seo_title;
$this->params['seo_description'] = $model->seo_description;
$this->params['seo_keywords'] = $model->seo_keywords;
$this->params['name'] = $model->name;

?>
<div class="header2">Контакты</div>
<div class="contactsPage">
    <div class="contactsPage__inner">
        <div class="contactsPage__left">
            <div class="contactsPage__item contactsPage__text">Мы всегда рады видеть Вас в нашей студии. Если у Вас возник вопрос или Вам необходима консультация, звоните по указанному ниже номеру телефона:</div>
            <hr>
            <div class="contactsPage__item">
                <div class="contactsPage__header">АДРЕС:</div>
                <div class="contactsPage__text">г. Москва, ул. Дмитрия Ульянова, д. 2/22</div>
            </div>
            <div class="contactsPage__item">
                <div class="contactsPage__header">ТЕЛЕФОН:</div>
                <div class="contactsPage__text">+7 915 255-40-00</div>
            </div>
            <div class="contactsPage__item">
                <div class="contactsPage__header">ГРАФИК РАБОТЫ:</div>
                <div class="contactsPage__text">Понедельник - Пятница с 10:00 до 20:00<br>Суббота, Воскресенье с 11:00 до 19:00</div>
            </div>
        </div>
        <div class="contactsPage__right">
            <?php
            $callbackForm = new CallbackForm();
            $form = ActiveForm::begin([
                'options' => [
                    'class' => 'contactsForm sendForm',
                    'id' => 'contactsForm'
                ],
            ]);?>
            <div class="contactsForm__text">Вы можете воспользоваться формой обратной<br>связи, чтобы задать интересующий Вас вопрос</div>
            <div class="contactsForm__inner">
                <?=$form->field($callbackForm, 'name')
                    ->textInput([
                        'class' => 'contactsForm__input'
                    ])?>
                <?=$form->field($callbackForm, 'phone')
                    ->textInput([
                        'class' => 'contactsForm__input'
                    ])?>

                <?=$form->field($callbackForm, 'email')
                    ->textInput([
                        'class' => 'contactsForm__input'
                    ])?>
                <?=$form->field($callbackForm, 'message')
                    ->textarea([
                        'class' => 'contactsForm__input'
                    ])?>
            </div>
            <button type="submit" class="contactsForm__submit">Отправить!</button>

            <?=$form->field($callbackForm, 'type')
                ->hiddenInput([
                    'value' => 'Заказан обратный звонок на сайте Studiovanilla'
                ])->label(false)?>

            <?=$form->field($callbackForm, 'BC')
                ->hiddenInput([
                    'value' => ''
                ])->label(false)?>
            <?php ActiveForm::end();?>
        </div>
    </div>
</div>

<div class="header2">Мы на карте</div>
<script src="//api-maps.yandex.ru/2.1/?lang=ru_RU" type="text/javascript"></script>
<div id="map"></div>

frontend/views/textpage/index.php
<?php

$this->params['seo_title'] = $model->seo_title;
$this->params['seo_description'] = $model->seo_description;
$this->params['seo_keywords'] = $model->seo_keywords;
$this->params['name'] = $model->name;

?>

frontend/views/textpage/service.php
<?php

$this->params['seo_title'] = $model->seo_title;
$this->params['seo_description'] = $model->seo_description;
$this->params['seo_keywords'] = $model->seo_keywords;
$this->params['name'] = $model->name;

?>

<div class="header2"><?=$model->name?></div>
<div class="servicePage">
    <div class="container">
        <div class="servicePage__inner">
            <?php foreach($serviceItems as $serviceItem) { ?>
                <div class="servicePage__item">
                    <div class="servicePage__itemName"><?=$serviceItem->name?></div>
                    <div class="servicePage__itemInfo">
                        <div class="servicePage__itemTime"><?=$serviceItem->time?></div>
                        <div class="servicePage__itemPrice"><?=$serviceItem->price?> Р</div>
                    </div>
                    <div class="servicePage__itemInner">
                        <div class="servicePage__itemImage" style="background-image: url(<?=$serviceItem->image?>);"></div>
                        <div class="servicePage__itemText"><?=$serviceItem->descr?></div>
                    </div>
                </div>
            <?php } ?>
        </div>
    </div>
</div>

<?=$this->render('@frontend/views/blocks/masters', ['masters' => $model->personal])?>